name: baileys mom
favicon: null
layout_spectrum: 0.25253
typography_spectrum: 0.14983
title: 'My son, Bailey'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1d9cd'
    - '#14131a'
    - '#c33722'
    - '#a49f99'
    - '#4e5351'
  brandStrength: 0.9478155367542058
  lightness: 0.2850640304386616
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
