name: baileys mom
favicon: null
layout_spectrum: 0.10629514651373029
typography_spectrum: 0.6603541527874768
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9478155367542058
  lightness: 0.2850640304386616
  saturation: 0.7021397915668786
  rhythmicContrast: 0.5396296593826264
purpose: []
